### ISSUE TITLE
Could you add a mock family name generator too ?

### ISSUE THREAD

**Issue by RoarGronmo** [PinkFrojd/mock_data#18]
Typical valus would be: 

"Smith"
"Jones"
"Anderson"
"Jameson"

**Comment by dinkopehar** [comment]
Hi @RoarGronmo . Thank you for taking interest in project.

I'll look into implementing the requested feature soon. I'm not working with dart on regular basis as I used to before so I think it will be simple as [lib/src/mock_name.dart](https://github.com/dinkopehar/mock_data/blob/master/lib/src/mock_name.dart) only called differently.

If you are in hurry, I'm also accepting PRs for this project, so feel free to make Pull Request before me 👍

**Comment by dinkopehar** [comment]
Hi @RoarGronmo 

I just pushed to `master` branch. I'm not going to publish my changes currently on [pub.dev](pub.dev) , but feel free to include this dependency from `master` branch or from commit using:

```
dependencies:
  mock_data:
    git:
      url: https://github.com/dinkopehar/mock_data.git
      ref: main # branch name
```
